name: Alert Composer Audit
on:
  push:
    branches:
      - master
jobs:
  check-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: glassmonenkey/actions-php-audit@v0.1
        name: checker
        id: checker
      - name: sample message
        run: echo "${{ steps.checker.outputs.message }}"